name: deploy-github-release

on:
  workflow_dispatch:

jobs:
  deploy-github-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      GITHUB_USERNAME: ${{ github.repository_owner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Create dll
        run: |
          dotnet publish src/Example/Example.csproj \
            --configuration Release \
            --output publish

      - name: Zip dll
        run: |
          mkdir -p release
          zip -r -j release/example.zip publish/

      - name: Deploy GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          token: ${{ secrets.REPOSITORY_TOKEN }}
          body_path: CHANGELOG.md
